export const SEND_OTP_REQUEST = 'SEND_OTP_REQUEST';
export const SEND_OTP_SUCCESS = 'SEND_OTP_SUCCESS';
export const SEND_OTP_FAILURE = 'SEND_OTP_FAILURE';
export const SEND_OTP_FINISH = 'SEND_OTP_FINISH';
export const SEND_OTP_CLEAR = 'SEND_OTP_CLEAR';

export const REGISTER_OTP_REQUEST = 'REGISTER_OTP_REQUEST';
export const REGISTER_OTP_SUCCESS = 'REGISTER_OTP_SUCCESS';
export const REGISTER_OTP_FAILURE = 'REGISTER_OTP_FAILURE';
export const REGISTER_OTP_FINISH = 'REGISTER_OTP_FINISH';
export const REGISTER_OTP_CLEAR = 'REGISTER_OTP_CLEAR';

export const UPDATE_AUTHUSER_REQUEST = 'UPDATE_AUTHUSER_REQUEST';
export const UPDATE_AUTHUSER_SUCCESS = 'UPDATE_AUTHUSER_SUCCESS';
export const UPDATE_AUTHUSER_FAILURE = 'UPDATE_AUTHUSER_FAILURE';
export const UPDATE_AUTHUSER_FINISH = 'UPDATE_AUTHUSER_FINISH';
export const UPDATE_AUTHUSER_CLEAR = 'UPDATE_AUTHUSER_CLEAR';

export const INFO_AUTHUSER_REQUEST = 'INFO_AUTHUSER_REQUEST';
export const INFO_AUTHUSER_SUCCESS = 'INFO_AUTHUSER_SUCCESS';
export const INFO_AUTHUSER_FAILURE = 'INFO_AUTHUSER_FAILURE';
export const INFO_AUTHUSER_FINISH = 'INFO_AUTHUSER_FINISH';

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';

export const CHECK_RAUTH_REQUEST = 'CHECK_RAUTH_REQUEST';
export const CHECK_RAUTH_SUCCESS = 'CHECK_RAUTH_SUCCESS';
export const CHECK_RAUTH_FAILURE = 'CHECK_RAUTH_FAILURE';
export const CHECK_RAUTH_FINISH = 'CHECK_RAUTH_FINISH';
