  
  // Action Types
  export const LIST_MESSAGES_REQUEST = 'LIST_MESSAGES_REQUEST';
  export const LIST_MESSAGES_SUCCESS = 'LIST_MESSAGES_SUCCESS';
  export const LIST_MESSAGES_FAILURE = 'LIST_MESSAGES_FAILURE';
  export const LIST_MESSAGES_FINISH = 'LIST_MESSAGES_FINISH';
  export const LIST_MESSAGES_CLEAR = 'LIST_MESSAGES_CLEAR';
  
  export const UPDATE_MESSAGE_REQUEST = 'UPDATE_MESSAGE_REQUEST';
  export const UPDATE_MESSAGE_SUCCESS = 'UPDATE_MESSAGE_SUCCESS';
  export const UPDATE_MESSAGE_FAILURE = 'UPDATE_MESSAGE_FAILURE';
  export const UPDATE_MESSAGE_FINISH = 'UPDATE_MESSAGE_FINISH';
  export const UPDATE_MESSAGE_CLEAR = 'UPDATE_MESSAGE_CLEAR';
  

  export const LIST_CHATROOMS_REQUEST = 'LIST_CHATROOMS_REQUEST';
  export const LIST_CHATROOMS_SUCCESS = 'LIST_CHATROOMS_SUCCESS';
  export const LIST_CHATROOMS_FAILURE = 'LIST_CHATROOMS_FAILURE';
  export const LIST_CHATROOMS_FINISH = 'LIST_CHATROOMS_FINISH';
  export const LIST_CHATROOMS_CLEAR = 'LIST_CHATROOMS_CLEAR';
  
  export const UPDATE_CHATROOM_REQUEST = 'UPDATE_CHATROOM_REQUEST';
  export const UPDATE_CHATROOM_SUCCESS = 'UPDATE_CHATROOM_SUCCESS';
  export const UPDATE_CHATROOM_FAILURE = 'UPDATE_CHATROOM_FAILURE';
  export const UPDATE_CHATROOM_FINISH = 'UPDATE_CHATROOM_FINISH';
  export const UPDATE_CHATROOM_CLEAR = 'UPDATE_CHATROOM_CLEAR';

  export const SELECT_CHATROOM = 'SELECT_CHATROOM';
  